# This is a basic workflow to help you get started with Actions

name: Cert Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Run Workflow
      id: write_file
      uses: timheuer/base64-to-file@v1.0.3
      with:
        fileName: 'temp.cert'
        encodedString: ${{ secrets.CERT }}
    - name: Some other step
      run: |
        cat ${{ steps.write_file.outputs.filePath }}
