# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main2 branch
  push:
    branches: [ main2 ]
  pull_request:
    branches: [ main2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: GitHub GraphQL API Query
      # You may pin to the exact commit or the version.
      # uses: octokit/graphql-action@5b35793a23d626e7528da63fc3b47a5bc06b628c
        uses: octokit/graphql-action@v2.2.1
          with:
          # Your GraphQL query, see https://developer.github.com/v4/
          query: |
          {
            repository(name: "actions-examples", owner: "evgenyrahman") {
              ref(qualifiedName: "main") {
                target {
                  ... on Commit {
                    id
                    history(first: 5) {
                      pageInfo {
                        hasNextPage
                      }
                      edges {
                        node {
                          messageHeadline
                          oid
                          message
                          author {
                            name
                            email
                            date
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
