name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      env: # Or as an environment variable
        NBD: ${{ secrets.nbd }}
      run: echo ${{ secrets.nbd }}
